name: Run tests
on:
  push:
    branches-ignore:
      - "main"

jobs:
  unit-testing:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          cli: 1.10.3.986
      - name: Execute unit tests
        run: "clojure -M:unit"
